# Generated by Django 6.0.5 on 2026-06-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_director_genre_film_director_film_gener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='gener',
            new_name='genres',
        ),
    ]
